enum { // VGUI Menu definitions
	MENU_DEFAULT = 1,
	MENU_INTRO,
	MENU_SPECHELP,
	MENU_STORE,
	MENU_STOREBUY,
	MENU_STORESELL,
	MENU_CONTAINER,
	MENU_STORAGE,
	MENU_NEWCHARACTER,
	MENU_STATS,
	MENU_SPAWN,
	MENU_LOCAL, // MiB MAR2015_01 [LOCAL_PANEL] - VGUI index for locan panel
	MENU_MAIN,
};
